###fetch all
get http://localhost:8080/api/learn/

###fetch by id
get http://localhost:8080/api/learn/1

### delete by id
delete http://localhost:8080/api/learn/23

### post
POST http://localhost:8080/api/learn
Content-Type: application/json

{
  "finnish": "Karkki",
  "english": "Candy"
}
### PATCH TEST
PATCH http://localhost:8080/api/learn/18
Content-Type: application/json

{
  "finnish": "Mug",
  "english": "Muki"
}
